### ISSUE TITLE
Export all extensions feature

### ISSUE THREAD

**Issue by NN---** [loop8ack/ExtensionPackTools#25]
There should be button to export all without selecting one by one.

**Comment by astrohart** [comment]
I second that emotion.  I have a large number of VS2019 extensions, and it would be helpful to be able to click one button to select all of them in one go -- rather than a manual process of clicking each check box one by one.
![fig01](https://user-images.githubusercontent.com/8261875/80917172-417c5980-8d2b-11ea-8345-348eb535ec7f.png)

**Comment by AizenSousuke** [comment]
Is the function already in the latest version? I saw the pull request & code but it isn't appearing in the modal.

**Comment by jakeafoster** [comment]
The update has not been sent to the store yet. 

I installed the updated version manually since it was quicker than clicking extensions one by one.

**Comment by astrohart** [comment]
I would like to recommend that a "Deselect All" button also be added.

In fast, I suggest the use of the "list builder pattern" for the dialog box, such as this example shown:

![image](https://user-images.githubusercontent.com/8261875/92937296-27f5c780-f419-11ea-83c9-90b8615e9a9f.png)

However, with Add All and Remove All buttons also.

**Comment by madskristensen** [comment]
I can release the latest version to the Marketplace. Can you please verify that the latest [CI build](https://www.vsixgallery.com/extension/4a196712-2c3f-4730-ad1d-e7cda4185eb2) works to your satisfaction?

**Comment by jakeafoster** [comment]
@astrohart I added a 'Deselect all' button as well. Please take a look below.
![2020-09-12_12-12-35](https://user-images.githubusercontent.com/46297995/92985461-fb63ad80-f4f5-11ea-8815-3a85875c23a4.png)

**Comment by jakeafoster** [comment]
Thanks, @madskristensen. It works okay for me.

**Comment by astrohart** [comment]
That is very nice, but what about the "OK" button? I am confused, once I've "selected" all my extensions that I want, how do I tell it to "do it?"

In my mind, the "Select All" and "Deselect All" buttons just change the state of the check boxes.  There should be an OK button in the dialog box (I suggest renaming the "Select" button "OK" and change it to have the default focus (i.e., a heavy bold border and it's pressed when the ENTER key is pressed)).

**Comment by astrohart** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/8261875/92987044-00404700-f48d-11ea-8a27-2d615eb076d5.png)

As shown in the image, there are "OK" and "Cancel" buttons.  The "Cancel" button, when clicked, closes the dialog box and does not do anything else (i.e., does not apply the user's settings in any way).  Pressing the ESCAPE key should also trigger the "Cancel" functionality.  Likewise, the "OK" button dismisses the dialog box and also applies the user's settings/takes the action of importing or exporting (for even more user-friendliness, detect whether the dialog is being brought up to Import or Export, and change the text of the "OK" button to "Export" or "Import," as appropriate).    The "OK" button should also be triggered by a press of the ENTER key.  Move the Select and Select All buttons to be aligned as shown, and this makes for a more pleasing layout.

**Comment by astrohart** [comment]
Fixed by via 02d134c.
