### ISSUE TITLE
OK button in dialog box should say "Import" when importing, "Export" when exporting, and should have a keyboard mnemonic

### ISSUE THREAD

**Issue by astrohart** [loop8ack/ExtensionPackTools#37]
To reproduce the issue:

1. Obtain **v0.6.66 or higher** of this extension.
2. Click the **Extensions** menu in VS2019, point to **Import and Export Extensions**, and then click **Export Extensions**.
3. The dialog box's "OK" button in the resulting dialog box is called **Select**.  I think **Export** would be better text for the button.
4. Likewise, if the user clicks the **Extensions** menu in VS2019, points to **Import and Export Extensions**, and then clicks **Import Extensions**, then the "OK" button is called **Install...** also misleading. I think **Import** (with no dots -- an "OK" button is a _command_ not an action that requires more work as dots imply) is a better name for the button.

Also, in the code, I recommend that the strings `&Import` and `&Export`, respectively, be utilized -- this way, if someone is physically handicapped to the point where they cannot utilize the mouse to click items, and they have to tab with the keyboard, they can press the `ALT` key.  This, combined with the `&Import` and/or `&Export` button text, makes the word **Import** have an underlined first letter, and likewise for **Export** on the button.  This is known as a _keyboard mnemonic character_.

NOTE: The **Cancel** button is never in need of such a mnemonic character, given that pressing the `ESC` key is the universal trigger for the **Cancel** button action.

**Comment by astrohart** [comment]
Was this dealt with via 44404e07fb02f074ca8f4fc76fa8d5615dbe67fd? If so, I respectfully request permission to close this Issue.

**Comment by astrohart** [comment]
Fixed via https://github.com/madskristensen/ExtensionPackTools/commit/44404e07fb02f074ca8f4fc76fa8d5615dbe67fd

**Comment by astrohart** [comment]
Hey Mads,

Any chance this can get pushed out in the next release?  Is that planned for sometime soon?

-Brian Hart

**Comment by madskristensen** [comment]
@astrohart I'll release a new version now. Thanks again

**Comment by astrohart** [comment]
May I please go ahead and submit a PR to update the screenshots and instructions in the docs (the .md files on here) before you release?

My concern is you releasing the next release and then have to do a documentation update and release *again*

**Comment by madskristensen** [comment]
Please go ahead

**Comment by astrohart** [comment]
OK. I won't be able to get to it for another day or so.
