### ISSUE TITLE
Version 0.6.72 not working.

### ISSUE THREAD

**Issue by jvsca** [loop8ack/ExtensionPackTools#40]
Version 0.6.72 not working:
When running Export Extensions...:
Warning dialog:
    Extension Manager 2019
    WindowStyIe.None is the only valid value for WindowStyIe
    when AllowsTransparency is true.

When running Import Extensions...:
Error dialog:
    WindowStyIe.None is the only valid value for WindowStyIe
    when AllowsTransparency is true.

Windows 10.0.19042.685.

**Comment by eobeda** [comment]
Same issue, same version, I'll add that export also fails with a different dialog box being displayed; but same basic message. Here are my VS settings:
Microsoft Visual Studio Professional 2019
Version 16.8.3

**Comment by jakeafoster** [comment]
I have sent a pull request that sets the windows style to none that fixes this issue.

**Comment by astrohart** [comment]
As per my previous comment, established desktop UI/UX guidelines call for a title bar on the window.  I believe the fix is to instead set `AllowsTransparency` to `false` instead.
