### ISSUE TITLE
Support for VS2022

### ISSUE THREAD

**Issue by CZEMacLeod** [loop8ack/ExtensionPackTools#46]
Like some of your other extensions - it would be great if this supported VS2022 such that we could load our extension sets from VS2019 more easily.
I understand that this stores the vsixId and that is not always the same from 2019 to 2022 due to package splitting...
Perhaps the store could be updated to automagically forward requests on to the new ID, or we could have a file on github somewhere with a virtual bundles list until that happens...

**Comment by madskristensen** [comment]
I'll add it to my list of extensions to convert

**Comment by madskristensen** [comment]
Grab it here: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ExtensionManager2022
