### ISSUE TITLE
Output extension information page URL and download URL in `extensions.vsext` on export

### ISSUE THREAD

**Issue by astrohart** [loop8ack/ExtensionPackTools#50]
Hi,

I was wondering if you can output the "marketplace name" of an extension in the `.vsext` file when doing an export.  

I mean the following:

![image](https://user-images.githubusercontent.com/8261875/149043971-49eaa983-30ec-40a8-9336-92bfba6a79d7.png)

Can I do a PR?

**Comment by madskristensen** [comment]
What do you mean by "output". Where exactly?

**Comment by madskristensen** [comment]
PRs always welcome

**Comment by astrohart** [comment]
When you do an “Export Extensions,” a file with a `.vsext` file is produced.  By “output,” I mean the contents of this file.

Brian

**Comment by astrohart** [comment]
Do you use `snake_case` or `camelCase` on your JSON properties?  It’s hard to tell because all the existing ones seem to one-word property names.

**Comment by astrohart** [comment]
> What do you mean by "output". Where exactly?

When one does an “Export Extensions,” a file with a `.vsext` file is produced.  By “output,” I mean the contents of this file.

Brian

**Comment by astrohart** [comment]
I modified the title of this issue to be more descriptive of my suggestion.  The upthrust of outputting URLs makes it easier to script the spinup of new developer workstations easier by parsing the "More Info URL" and "Download URL" from the `extensions.vsext` file produced by the `Export Extensions` menu item.

This functionality is aimed at IT staff at enterprises who have to set up large numbers of developer workstations in an automated, unattended fashion.

The use case is:

1. Create a Reference PC containing an installed Visual Studio, this extension, and other favorite extensions.
2. Run the **Export Extensions** command to export the list of extensions to a `.vsext` file.
3. The `.vsext` script, along with a piece of code that parses the URLs and downloads the extensions, can be deployed over a large number of user workstations to download each extension's `.vsix` file and then use `VSIXInstaller.exe` to install each.

**Comment by madskristensen** [comment]
Visual Studio doesn't know what to do with .vsext files if they don't contain the ID. Perhaps, we could add a separate field to include the URL or something like that

**Comment by astrohart** [comment]
> Visual Studio doesn't know what to do with .vsext files if they don't contain the ID.

I am not 100% sure what you mean.  I am merely talking about adding fields not removing any.

**Comment by madskristensen** [comment]
Gotcha. Adding fields is fine to do

**Comment by astrohart** [comment]
@madskristensen Please see PR #51.  Thank you.
