### ISSUE TITLE
Question: Is there a plan to pack the 3 DLLs into a NuGet?

### ISSUE THREAD

**Issue by MathieuSevegny** [loop8ack/ExtensionPackTools#64]
I was wondering if there is a plan to pack all the DLLs into a NuGet package. 

The DLLs in question :

- [Microsoft.VisualStudio.ExtensionEngine.dll](https://github.com/madskristensen/ExtensionPackTools/blob/master/lib/2022/Microsoft.VisualStudio.ExtensionEngine.dll)
- [Microsoft.VisualStudio.ExtensionManager.dll](https://github.com/madskristensen/ExtensionPackTools/blob/master/lib/2022/Microsoft.VisualStudio.ExtensionManager.dll)
- [Microsoft.VisualStudio.ExtensionsExplorer.dll](https://github.com/madskristensen/ExtensionPackTools/blob/master/lib/2022/Microsoft.VisualStudio.ExtensionsExplorer.dll)

I found [this NuGet](https://www.nuget.org/packages/VSSDK.ExtensionManager/) containing only one of them but I didn't find an official one.

I see a lot of possibilities with those DLLs and I think that a NuGet with those 3 can be interesting for others.

**Comment by madskristensen** [comment]
No, I don't believe the extensibility team will do that

**Comment by MathieuSevegny** [comment]
Okay, thank you for the response!
