### ISSUE TITLE
17.9 Preview 2: Method 'get_IsPublisherDomainVerified' does not have an implementation

### ISSUE THREAD

**Issue by richardcox13** [loop8ack/ExtensionPackTools#80]
I've just updated to 17.9 Preview 2 Ent

And exporting extension list reports:

```
Method 'get_IsPublisherDomainVerified' in type 'ExtensionManager.V17.GalleryEntry'
from assembly 'ExtensionManager2022.V17, Version=1.0.0.0,
Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

Extension Manager V1.2.77

This was fine a few days with preview 1.

Could this be related to the new feature "Benefit Awareness Diamond for Visual Studio Enterprise and Professional Subscribers" ([release notes](https://learn.microsoft.com/en-gb/visualstudio/releases/2022/release-notes-preview#benefit-awareness-diamond-for-visual-studio-enterprise-and-professional-subscribers)?

**Comment by loop8ack** [comment]
It is due to the Visual Studio Update, but because internally used DLLs are used, which are constantly updated.

I have just released a new update, please test if it works for you again.

**Comment by richardcox13** [comment]
And the new update fixes export in current preview.

And also good in 17.8.3.

Thanks
